[package]
name = "bevy_2d_menu_mask_transition"
description = "A Bevy plugin for creating smooth menu transitions with customizable masks."
license = "MIT"
version = "0.2.0"
edition = "2024"
repository = "https://github.com/Lan-Game-Studios/bevy-2d-menu-mask-transitions"
homepage = "https://github.com/Lan-Game-Studios/bevy-2d-menu-mask-transitions"
documentation = "https://docs.rs/bevy_2d_menu_mask_transition"
readme = "README.md"
keywords = [
    "bevy",
    "plugin",
    "2d",
    "transitions",
    "menu",
]
categories = ["game-engines", "graphics", "rendering"]
exclude = ["assets/*", "docs/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy_render = "0.18"
bevy_ecs = "0.18"
bevy_app = "0.18"
bevy_asset = "0.18"
bevy_time = "0.18"
bevy_ui = "0.18"
bevy_ui_render = "0.18"
bevy_reflect = "0.18"
bevy_window = "0.18"
bevy_state = "0.18"
bevy_image = "0.18"
bevy_shader = "0.18"
bevy_log = "0.18"

[dev-dependencies]
bevy = { version = "0.18", default-features = false, features = [
    "bevy_asset",
    "bevy_core_pipeline",
    "bevy_render",
    "bevy_sprite",
    "bevy_text",
    "bevy_ui",
    "bevy_ui_render",
    "bevy_winit",
    "default_font",
    "x11",
    "webp",
] }

[workspace.lints.clippy]
type_complexity = "allow"
